"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "User",
      [
        {
          UserId: "bfeddaf0-a068-447a-9df5-b6252da20ba5",
          FirstName: "John",
          LastName: "Doe",
          UserName: "John-Doe",
          Email: "wellington.sydney1@gmail.com",
          Password: "31051986",
          Avatar: "avatar1.svg",
          UpdatedAt: new Date(),
          CreatedAt: new Date(),
        },
        {
          UserId: "1c09f106-742b-48c2-9eb5-56e35e31b8ff",
          FirstName: "Jane",
          LastName: "Smith",
          UserName: "Jane-Smith",
          Email: "jane.smith@example.com",
          Password: "12345678",
          Avatar: "avatar2.svg",
          UpdatedAt: new Date(),
          CreatedAt: new Date(),
        },
        {
          UserId: "9c35b07e-5ce7-4b09-8f0d-4d92f129da3a",
          FirstName: "Michael",
          LastName: "Johnson",
          UserName: "Michael-Johnson",
          Email: "michael.johnson@example.com",
          Password: "password123",
          Avatar: "avatar3.svg",
          UpdatedAt: new Date(),
          CreatedAt: new Date(),
        },
        {
          UserId: "6b2c42d7-76f0-42af-97c9-12b9d2d5d8cd",
          FirstName: "Emily",
          LastName: "Brown",
          UserName: "Emily-Brown",
          Email: "emily.brown@example.com",
          Password: "98765432",
          Avatar: "avatar4.svg",
          UpdatedAt: new Date(),
          CreatedAt: new Date(),
        },
        {
          UserId: "0fe71421-8997-4e82-9bde-6f2fcd1c66bc",
          FirstName: "Daniel",
          LastName: "Wilson",
          UserName: "Daniel-Wilson",
          Email: "daniel.wilson@example.com",
          Password: "abc123",
          Avatar: "avatar5.svg",
          UpdatedAt: new Date(),
          CreatedAt: new Date(),
        },
        {
          UserId: "dc5436a1-50a4-4d96-8d79-bb0b69d1cde6",
          FirstName: "Olivia",
          LastName: "Taylor",
          UserName: "Olivia-Taylor",
          Email: "olivia.taylor@example.com",
          Password: "passw0rd",
          Avatar: "avatar6.svg",
          UpdatedAt: new Date(),
          CreatedAt: new Date(),
        },
        {
          UserId: "ec16a42c-3cc6-40db-967d-224f2f3372a2",
          FirstName: "Ethan",
          LastName: "Anderson",
          UserName: "Ethan-Anderson",
          Email: "ethan.anderson@example.com",
          Password: "qwertyuiop",
          Avatar: "avatar7.svg",
          UpdatedAt: new Date(),
          CreatedAt: new Date(),
        },
        {
          UserId: "783febb5-f0ed-4498-b3e3-85fbd99f7ea7",
          FirstName: "Sophia",
          LastName: "Thomas",
          UserName: "Sophia-Thomas",
          Email: "sophia.thomas@example.com",
          Password: "thomas123",
          Avatar: "avatar8.svg",
          UpdatedAt: new Date(),
          CreatedAt: new Date(),
        },
        {
          UserId: "c3c0e791-59fd-4789-8f29-18d9b57a7e47",
          FirstName: "William",
          LastName: "Martinez",
          UserName: "William-Martinez",
          Email: "william.martinez@example.com",
          Password: "password",
          Avatar: "avatar9.svg",
          UpdatedAt: new Date(),
          CreatedAt: new Date(),
        },
        {
          UserId: "41f6d16f-78d0-468b-a6e4-f66be2c0d9df",
          FirstName: "Ava",
          LastName: "Garcia",
          UserName: "Ava-Garcia",
          Email: "ava.garcia@example.com",
          Password: "abcdefg",
          Avatar: "avatar1.svg",
          UpdatedAt: new Date(),
          CreatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("User", null, {});
  },
};
